---
- hosts: homologa01
  become: true
  remote_user: sysadmin
  tasks:
  - name: Desabilitar a protecao de leitura /etc/resolv.conf
    command: "chattr -i /etc/resolv.conf"

  - name: Copiar o arquivo com DNS padrao da empresa
    copy: 
      src=./files/resolv.conf
      dest=/etc/resolv.conf

  - name: Habilitar a protecao de leitura /etc/resolv.conf
    command: "chattr +i /etc/resolv.conf"

  - name: Alterando arquivo com repositorios do debian
    copy:
      src=./files/sources.list
      dest=/etc/apt/sources.list

  - name: atualizar o repositorio
    apt: 
      update_cache=yes

  - name: instalando programas pós instalacao
    apt:
      pkg:
        - build-essential
        - module-assistant
        - python-apt
        - python3
        - python3-apt
        - python3-pip
        - vim
        - git
        - sl
        - net-tools
        - tree
        - htop
      state: latest

  - name: Realizando a limpeza
    apt:
      autoremove: yes
      autoclean: yes

  - name: Copiar o arquivo para personalizar o vim
    copy:
      src=./files/vimrc 
      dest=/etc/vim/vimrc

  - name: Tornar o vim o editor de texto padrao
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
      link: /usr/bin/vim
      priority: 30
